# .azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @ionic/cli
    npm install
  displayName: 'Install dependencies'

- script: |
    ionic build --prod
    npx cap add ios
  displayName: 'Build Ionic app'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'your-certificate.p12'
    certPwd: '$(APPLE_CERTIFICATE_PASSWORD)'
    keychain: 'temp'
    removeCert: true
  displayName: 'Install Apple Certificate'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'your-profile.mobileprovision'
    removeProfile: true
  displayName: 'Install Apple Provisioning Profile'

- script: |
    cd ios/App
    xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath $(Build.ArtifactStagingDirectory)/App.xcarchive archive
    xcodebuild -exportArchive -archivePath $(Build.ArtifactStagingDirectory)/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $(Build.ArtifactStagingDirectory)
  displayName: 'Build and Archive iOS app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Artifact'
